server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: altees
logging:
  level:
    org:
      springframework:
                  data:
                    mongodb: DEBUG
  com: TRACE

